# Server port
server:
  port: 8080
  context-path: /zportal

# Spring properties
spring:
  # JPA properties
  jpa:
    database: POSTGRESQL

# Logging properties
logging:
  # Logging file
  file: /var/log/zautomate/zportal.log
  # Logging Levels
  level:
    org.springframework.web: ERROR
    com.zautomate.zportal.modules: DEBUG
  # Logging Patterns
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n)"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n)"

    
